from pathlib import Path
import json

RID = "BRRK-BETA-DETERIORATION-BTC-TAKEOVER-DIAGNOSTIC-0059"
ROOT = Path('.')
REGISTRY = ROOT / 'config/research_registry.json'
STATE = ROOT / 'docs/CURRENT_STATE.md'
OUT = ROOT / 'research/brrk_beta_deterioration_btc_takeover_diagnostic_0059'

record = {
  "research_id": RID,
  "research_family_id": "BRRK_BETA_TO_BTC_DEFENSIVE_HANDOFF",
  "research_domain": "RISK_CONTROL",
  "research_governance_version": 1,
  "governance_mode": "PROGRAM_GOVERNED_V1",
  "objective_type": "MECHANISM_TEST",
  "created_at": "2026-08-12T23:03:00Z",
  "created_before_result": True,
  "question": "Does the single frozen low-dimensional causal deterioration state in symmetric ETH/SOL Beta contain recurrent monotone information about subsequent BTC-over-Beta continuation value across the full preregistered 20/60/120/240-day horizon family before any threshold, allocation map or switching economics is defined?",
  "hypothesis": "If Beta continuation value genuinely deteriorates before BTC becomes the preferable defensive anchor, the frozen equal-weight state combining Beta fast-vs-slow trend disagreement, Beta distance below its 60-session high and Beta/BTC fast-vs-slow relative disagreement should have positive recurrent monotone association with future BTC-over-Beta continuation value at all four frozen horizons.",
  "hypothesis_origin": "RESULT_INFORMED_MECHANISM_FORK_AFTER_IMMUTABLE_0058_NO_STABLE_PARAMETER_PLATEAU_USING_ONLY_PRE_0058_STATE_FAMILIES_AND_FROZEN_0059_DESIGN",
  "economic_mechanism": "A weakening symmetric ETH/SOL Beta tier can lose continuation value relative to BTC through internal trend deterioration and BTC defensive leadership. 0059 tests only whether one frozen continuous causal deterioration state orders subsequent BTC-over-Beta continuation value. It defines no threshold, allocation response, switching strategy, NAV path, transaction-cost model or BTC-to-cash rule.",
  "primary_target": "MONOTONE_BTC_OVER_BETA_CONTINUATION_INFORMATION_SIMULTANEOUSLY_ACROSS_20_60_120_240_DAY_FORWARD_HORIZONS",
  "primary_metric": "FULL_SAMPLE_SPEARMAN_PLUS_240_ORIGIN_MOVING_BLOCK_SIMULTANEOUS_ONE_SIDED_95PCT_LCB_ACROSS_ALL_FOUR_HORIZONS",
  "secondary_metrics": ["four_block_chronological_recurrence_of_positive_all_horizon_spearman", "D1_D2_D3_target_spearman_descriptive_only", "D1_D2_D3_spearman_redundancy_matrix_and_effective_rank_descriptive_only", "shared_complete_case_origin_count_and_dates"],
  "feature_families": ["SYMMETRIC_BETA_FAST_SLOW_TREND_DETERIORATION", "SYMMETRIC_BETA_60_SESSION_DISTANCE_BELOW_HIGH", "SYMMETRIC_BETA_VS_BTC_FAST_SLOW_RELATIVE_DETERIORATION"],
  "horizon": "BINANCE_SPOT_UTC_DAILY_RESEARCHER_EXPOSED_DEVELOPMENT_HISTORY_THROUGH_2026-08-02_WITH_SHARED_CAUSAL_ORIGINS_AND_FORWARD_TARGETS_20_60_120_240_DAYS",
  "universe": ["BTC", "ETH", "SOL"],
  "development_dataset_refs": ["BRRK-LEADERSHIP-ROTATION-0048-EXPOSED-HIST-V1"],
  "validation_dataset_refs": [],
  "sealed_dataset_refs": [],
  "declared_variant_budget": 1,
  "actual_variants_evaluated": 0,
  "parameter_candidate_count": 1,
  "stopping_rule": "After this preregistration merges, implement exactly one frozen 0059 mechanism diagnostic on an implementation-only branch using synthetic/toy/contract tests only. After a separately merged controlled-execution boundary, execute exactly one valid DEVELOPMENT historical measurement. Any valid result closes 0059 to same-ID rerun, feature/horizon/reweighting/support/bootstrap change or rescue. A durable attempt marker removes same-ID automatic recomputation authority.",
  "success_criteria": ["G0 immutable design/source/dataset/interface/variant/result-persistence integrity passes.", "G1 at least 1440 identical shared complete-case origins remain, equal to at least six complete 240-origin longest-target dependence blocks.", "G2 full-sample Spearman rho(S,Y_h) is strictly positive for every h in {20,60,120,240}.", "G3 at least three of four deterministic equal-as-possible chronological blocks have strictly positive Spearman at all four horizons simultaneously.", "G4 all four simultaneous one-sided 95% moving-block-bootstrap lower confidence bounds are strictly positive using block length 240, 10000 replicates and seed 1844716895.", "Only G0-G4 full pass produces PASS_MECHANISM_INFORMATION_STAGE_ELIGIBLE; this creates only new-ID translation/calibration eligibility."],
  "failure_criteria": ["Any immutable identity, causal timing, formula, variant-budget, forbidden-computation or persistence-contract violation is INVALID_EXECUTION.", "G0 pass with fewer than 1440 shared origins produces FAIL_INSUFFICIENT_CAUSAL_SUPPORT.", "G0-G1 pass with any full-sample rho_h <= 0, or a constant state/target making Spearman undefined, produces FAIL_NO_MONOTONE_CONTINUATION_INFORMATION.", "G0-G2 pass with fewer than three positive-all-horizon chronological blocks produces FAIL_TEMPORAL_INSTABILITY.", "G0-G3 pass with any simultaneous one-sided 95% LCB <= 0 produces FAIL_DEPENDENCE_AWARE_ROBUSTNESS.", "Component diagnostics, favorable single horizons, 0058 argmax or any descriptive plot cannot rescue a failed gate."],
  "allowed_followup": ["Only PASS_MECHANISM_INFORMATION_STAGE_ELIGIBLE may motivate a new separately designed/preregistered state-to-allocation translation or parameter-calibration research ID.", "Any later parameter identification must be systematic and separated from a subsequent fixed-parameter validation ID.", "A genuinely independent OOS claim requires a separately governed future-only protocol."],
  "forbidden_followup": ["No same-ID trading threshold, hysteresis, allocation weight, BTC/Beta switching rule, NAV/CAGR/MDD/cost optimization or portfolio economics.", "No same-ID reweighting/pruning/addition of D1/D2/D3 and no extra indicator/model rescue.", "No same-ID horizon addition/removal or winning-horizon selection.", "No same-ID support relaxation, temporal repartition, bootstrap block/replicate/seed/quantile change or alternative association statistic after output.", "No reuse of 0058 L=120,kappa=0.5, local surface geometry, gradient/Hessian values, grid zoom, threshold relaxation or alternate normalization.", "No reopening 0057 ETH/SOL micro-timing and no BTC-to-cash, leverage, shorting, signing, order submission or production authorization.", "No canonical BRRK or Phase 6 modification."],
  "researcher_decisions": ["Design authority is research/governance/BRRK_BETA_DETERIORATION_BTC_TAKEOVER_DIAGNOSTIC_0059_DESIGN_FREEZE_2026-08-13.md merged by PR #216 at 444e0ee6422e541e3d602ca0272200217834e6d8 before preregistration.", "0058 is immutable FAIL_NO_STABLE_PARAMETER_PLATEAU. Its exposed descriptive L=120,kappa=0.5 maximum and complete surface have zero 0059 parameter authority.", "0059 is a new-target pure mechanism diagnostic rather than a parameter descendant.", "Beta proxy is b=0.5*log(ETH)+0.5*log(SOL), B=exp(b); relative proxy is z=b-log(BTC), R=exp(z). No dynamic ETH/SOL leader selection exists.", "Trend mathematics are hash-bound to 0047 engine blob 059b55961e279dab41ba29b5b017de0922e4f33c: horizons 20/60/120/240; FAST weights .15/.25/.30/.30; SLOW weights .10/.20/.30/.40; tanh of log momentum divided by same-horizon sample-volatility scale times sqrt(h).", "D1 raw is SLOW(B)-FAST(B); D2 raw is the 0059-design-explicit log(trailing60 high(B)/B); D3 raw is SLOW(R)-FAST(R).", "Each raw axis uses causal z normalization hash-bound to 0043 implementation blob 642e795a807b1210b97a9683279553fb39c2e0ce: trailing252 including t, min60, sample std ddof1, zero std NaN, clip [-3,+3].", "Joint S is exactly the equal-weight mean of three finite normalized axes. Separate axes are descriptive only and cannot select or reweight the candidate.", "Future Beta comparator is origin-reset arithmetic 50/50 wealth W_BETA=0.5*ETH[t+h]/ETH[t]+0.5*SOL[t+h]/SOL[t], not an average log-return/geometric-mean substitute. Y_h=log(W_BTC/W_BETA).", "All four horizons 20/60/120/240 use one identical shared complete-case origin set.", "Nominal first state origin 2021-06-06, last shared origin 2025-12-05 and count 1644 are calendar/formula derivations only; no 0059 target value or association was read to obtain them.", "Support N>=1440 is six complete 240-origin blocks because 240 is the longest overlapping target; this scale is not estimated from outcomes.", "Primary association is Spearman with average ranks. No minimum effect-size threshold is imposed because economic relevance/translation belongs to a later new ID.", "Temporal recurrence uses four deterministic equal-as-possible chronological blocks and requires at least three blocks with all four rho_h>0.", "Dependence inference inherits the 0058 non-circular moving-block sampling and Type-7 centered-max simultaneous LCB semantics; block length is prospectively 240. Replicates=10000, seed=1844716895.", "Unique execution must losslessly persist origin-level state and all four W_BTC/W_BETA/Y targets plus block assignment.", "All source history is researcher-exposed DEVELOPMENT. PASS is not independent OOS and cannot authorize a strategy or production."],
  "research_process_complexity": {"declared_parameter_candidates": ["ONE_FIXED_STATE=D1_D2_D3_EQUAL_WEIGHT", "TREND_HORIZONS=20_60_120_240", "CAUSAL_Z=TRAILING252_MIN60_DDOF1_CLIP3", "TARGET_HORIZONS=20_60_120_240_ALL_REQUIRED", "SUPPORT_MIN=1440", "TEMPORAL=FOUR_EQUAL_REQUIRE3_ALL_HORIZONS_POSITIVE", "BOOTSTRAP=NONCIRCULAR_MBB240_X10000_SEED1844716895_SIMULTANEOUS95_LCB"], "actual_parameter_candidates_evaluated": [], "universes_evaluated": ["BINANCE_SPOT_BTC_ETH_SOL"], "horizons_evaluated": ["FORWARD_CONTINUATION_20_60_120_240_ALL_SIMULTANEOUS"], "rebalance_variants": [], "feature_representations": ["ONE_EQUAL_WEIGHT_D1_D2_D3_CONTINUOUS_DETERIORATION_STATE"], "special_cases_introduced": ["D2_LOG_TRAILING60_HIGH_DISTANCE_EXPLICIT_0059_DESIGN", "IDENTICAL_COMPLETE_CASE_ORIGINS_ACROSS_ALL_TARGET_HORIZONS", "PASS_ONLY_UNLOCKS_NEW_ID_TRANSLATION_CALIBRATION"], "validation_exposure_event_refs": [], "related_family_trials": 1},
  "lineage_edges": [{"relation": "RESULT_INFORMED", "ref_research_id": "BRRK-BETA-BTC-CONTINUATION-PARAMETER-GEOMETRY-0058", "provenance_status": "FACT", "evidence_ref": "research/brrk_beta_btc_continuation_parameter_geometry_0058/CLOSEOUT.json"}, {"relation": "MECHANISM_FORK", "ref_research_id": "BRRK-BETA-BTC-CONTINUATION-PARAMETER-GEOMETRY-0058", "provenance_status": "FACT", "evidence_ref": "research/governance/BRRK_BETA_DETERIORATION_BTC_TAKEOVER_DIAGNOSTIC_0059_DESIGN_FREEZE_2026-08-13.md"}, {"relation": "RESULT_INFORMED", "ref_research_id": "BRRK-EXHAUSTION-STATE-0044", "provenance_status": "FACT", "evidence_ref": "research/brrk_exhaustion_state_0044/PRIMARY_RESULT.json"}],
  "result_status": "PREREGISTERED_NOT_RUN",
  "failure_reason": None,
  "promotion_state": "NONE",
  "evidence_refs": [],
  "decision_refs": ["research/governance/BRRK_BETA_DETERIORATION_BTC_TAKEOVER_DIAGNOSTIC_0059_DESIGN_FREEZE_2026-08-13.md", "research/brrk_beta_deterioration_btc_takeover_diagnostic_0059/PREREGISTRATION.json", "research/brrk_beta_deterioration_btc_takeover_diagnostic_0059/DATASET_DECLARATION.json", "docs/CURRENT_STATE.md"],
  "production_relevance": "Research-only DEVELOPMENT mechanism-information diagnostic. A full PASS can only make a separately governed state-to-allocation translation/calibration study eligible; it cannot modify canonical BRRK, Phase 6 or confer production/signing/order authority.",
  "production_authorized": False,
  "provenance_status": "FACT",
  "governed_path_prefixes": ["research/brrk_beta_deterioration_btc_takeover_diagnostic_0059/"],
  "notes": ["0059 DESIGN merged before numerical/data preregistration.", "0058 and 0057 remain immutable closed failures and cannot be rerun or rescued.", "No 0059 historical target value, Spearman correlation, bootstrap result or portfolio economic output existed when this owner/preregistration was frozen.", "BTC-to-cash remains outside scope."]
}

prereg = {
  "schema_version": 1, "research_id": RID, "research_family_id": "BRRK_BETA_TO_BTC_DEFENSIVE_HANDOFF", "research_domain": "RISK_CONTROL", "research_governance_version": 1, "governance_mode": "PROGRAM_GOVERNED_V1", "objective_type": "MECHANISM_TEST", "created_before_result": True, "stage": "NUMERICAL_DATA_PREREGISTRATION", "result_status": "PREREGISTERED_NOT_RUN", "actual_variants_evaluated": 0,
  "design_authority": {"path": "research/governance/BRRK_BETA_DETERIORATION_BTC_TAKEOVER_DIAGNOSTIC_0059_DESIGN_FREEZE_2026-08-13.md", "design_pr": 216, "design_merge_sha": "444e0ee6422e541e3d602ca0272200217834e6d8", "design_blob_sha": "f532978a97f1a79a542ca09bf6fa9cb070a4c1d6", "design_changed_after_merge": False},
  "research_role": "PURE_MECHANISM_DIAGNOSTIC_NOT_PARAMETER_CALIBRATION_NOT_FIXED_STRATEGY_VALIDATION",
  "variant_budget": {"declared_candidate_representations": 1, "declared_parameter_candidates": 1, "actual_variants_evaluated_before_execution": 0, "feature_tournament_allowed": False, "horizon_selection_allowed": False, "threshold_search_allowed": False, "portfolio_variant_allowed": False},
  "immutable_bindings": {"market_evidence": {"path": "research/brrk_beta_handoff_0047/evidence/MARKET_EVIDENCE.json", "blob_sha": "64ebf5c6deaf3f34dbeac715378f196ff0f4fafe", "payload_sha256": "d1cd28bc76f2cd8ee0486287fc50b49e5451355a3e75132a2de5b30c15af3193"}, "0047_trend_source": {"path": "research/brrk_beta_handoff_0047/engine.py", "blob_sha": "059b55961e279dab41ba29b5b017de0922e4f33c"}, "0043_causal_z_source": {"path": "research/governance/brrk_exhaustion_event_study.py", "blob_sha": "642e795a807b1210b97a9683279553fb39c2e0ce"}, "0058_closeout": {"path": "research/brrk_beta_btc_continuation_parameter_geometry_0058/CLOSEOUT.json", "blob_sha": "2412d72780fcd10f3b97083b231084a2c103068f", "status": "FAIL_NO_STABLE_PARAMETER_PLATEAU", "closed": True, "historical_argmax_parameter_authority": False}},
  "data_contract": {"dataset_slice_ref": "BRRK-LEADERSHIP-ROTATION-0048-EXPOSED-HIST-V1", "dataset_id": "BINANCE-SPOT-BTC-ETH-SOL-UTC-DAILY-OHLCV-TRADES", "source_common_start": "2020-08-11T00:00:00Z", "source_common_end": "2026-08-02T00:00:00Z", "source_common_rows": 2183, "assets_consumed": ["BTC", "ETH", "SOL"], "field_consumed": "daily_close", "resolution": "1D", "semantic_timezone": "UTC", "source_index_representation": "UTC_NORMALIZED_TZ_NAIVE_DAILY_DATES", "network_fetch_allowed": False, "replacement_dataset_allowed": False, "synthetic_fill_allowed": False, "researcher_exposed_history": True, "data_budget": "DEVELOPMENT", "independent_oos": False},
  "representation": {"beta_log_proxy": "b_t=0.5*log(ETH_t)+0.5*log(SOL_t)", "beta_price_proxy": "B_t=exp(b_t)", "relative_log_proxy": "z_t=b_t-log(BTC_t)", "relative_price_proxy": "R_t=exp(z_t)", "trend_horizons": [20,60,120,240], "FAST_weights": [0.15,0.25,0.30,0.30], "SLOW_weights": [0.10,0.20,0.30,0.40], "trend_formula": "tanh(log(P_t/P_(t-h))/(sample_std_ddof1(dlogP,trailing_h_including_t)*sqrt(h)))", "D1_raw": "TREND_SLOW(B)-TREND_FAST(B)", "D2_raw": "log(max(B_(t-59)..B_t)/B_t)", "D3_raw": "TREND_SLOW(R)-TREND_FAST(R)", "causal_z": "trailing252_including_t,min60,sample_std_ddof1,zero_std_nan,clip[-3,+3]", "joint_state": "S=(D1_z+D2_z+D3_z)/3", "axis_reweighting_allowed": False},
  "target_contract": {"horizons_days": [20,60,120,240], "W_BETA": "0.5*(ETH_(t+h)/ETH_t)+0.5*(SOL_(t+h)/SOL_t)", "W_BTC": "BTC_(t+h)/BTC_t", "Y": "log(W_BTC/W_BETA)", "identical_shared_origins": True, "winning_horizon_selection_allowed": False, "geometric_mean_beta_substitution_allowed": False},
  "support_contract": {"nominal_first_joint_state_origin": "2021-06-06T00:00:00Z", "nominal_last_shared_origin": "2025-12-05T00:00:00Z", "nominal_shared_origin_count": 1644, "nominal_values_are_calendar_formula_derivations_only": True, "G1_min_shared_origins": 1440, "G1_equivalent": "six complete 240-origin dependence blocks", "actual_support_measured_only_in_unique_execution": True},
  "association_contract": {"statistic": "Spearman(S,Y_h) on identical shared origins", "rank_ties": "average", "G2_rule": "all four rho_h>0", "constant_state_or_target_policy": "FAIL_NO_MONOTONE_CONTINUATION_INFORMATION", "minimum_effect_size_gate": None},
  "temporal_contract": {"partition": "q,r=divmod(N,4); first r chronological blocks q+1 rows, others q", "nominal_sizes_if_N1644": [411,411,411,411], "positive_block": "all four rho_h>0", "G3_rule": "at least 3 of 4 positive blocks"},
  "bootstrap_contract": {"method": "aligned non-circular moving-block bootstrap", "block_length": 240, "replicates": 10000, "seed": 1844716895, "starts": "uniform-with-replacement from 0..N-L inclusive", "assembly": "draw full contiguous blocks until >=N then truncate", "replicate_statistic": "four Spearman rho_h", "simultaneous_error": "M_b=max_h(rho_obs_h-rho_boot_b_h)", "q95": "numpy quantile 0.95 method=linear / Type-7", "LCB_h": "rho_obs_h-q95", "G4_rule": "all four LCB_h>0", "sampling_semantics_inherited_from_0058_engine_blob": "690e029588d6ff453eaabfa1e4ce5a7f3df2f139"},
  "diagnostics": {"component_target_spearman": "D1_z,D2_z,D3_z vs each target; non-gating", "component_redundancy": "3x3 Spearman matrix", "effective_rank": "entropy effective rank of nonnegative correlation eigenvalues; descriptive only", "selection_authority": False},
  "classification_precedence": ["INVALID_EXECUTION", "FAIL_INSUFFICIENT_CAUSAL_SUPPORT", "FAIL_NO_MONOTONE_CONTINUATION_INFORMATION", "FAIL_TEMPORAL_INSTABILITY", "FAIL_DEPENDENCE_AWARE_ROBUSTNESS", "PASS_MECHANISM_INFORMATION_STAGE_ELIGIBLE"],
  "result_persistence_contract": {"unique_execution_lossless_origin_panel_required": True, "origin_panel_required_fields": ["origin_date","b_log_beta","z_log_beta_over_btc","D1_raw","D2_raw","D3_raw","D1_z","D2_z","D3_z","S","WBTC_20","WBETA_20","Y_20","WBTC_60","WBETA_60","Y_60","WBTC_120","WBETA_120","Y_120","WBTC_240","WBETA_240","Y_240","chronological_block_id"], "primary_result_required": ["classification","gates","shared_origin_count","shared_origin_start","shared_origin_end","full_sample_rho_by_horizon","temporal_block_rho_by_horizon","bootstrap_q95","simultaneous_lcb_by_horizon","component_target_spearman","component_redundancy_matrix","component_eigenvalues","component_effective_rank","actual_variants_evaluated"], "result_schema_hash_frozen_before_controlled_execution": True, "closeout_may_not_remeasure_targets": True},
  "execution_firewall": {"historical_target_values_during_preregistration": False, "historical_association_metrics_during_preregistration": False, "historical_target_values_during_implementation_only": False, "implementation_real_market_loader_allowed": False, "implementation_tests": "synthetic/toy/contract only", "real_execution_before_controlled_boundary_merge": False, "portfolio_nav_under_0059": False, "transaction_cost_economics_under_0059": False, "entry_exit_threshold_under_0059": False, "allocation_mapping_under_0059": False},
  "followup_contract": {"PASS_authority": "NEW_ID_SYSTEMATIC_STATE_TO_ALLOCATION_TRANSLATION_OR_PARAMETER_CALIBRATION_ONLY", "PASS_does_not_freeze_trading_parameter": True, "PASS_does_not_validate_strategy": True, "FAIL_closes_same_id_rescue": True, "0058_argmax_or_local_geometry_use": False, "BTC_to_cash_opened": False, "ETH_SOL_micro_timing_reopened": False, "canonical_strategy_changed": False, "phase6_changed": False, "production_authorized": False, "signature_authorized": False, "order_submission_authorized": False}
}

dataset = {
  "research_id": RID,
  "dataset_reuse": {"dataset_slice_id": "BRRK-LEADERSHIP-ROTATION-0048-EXPOSED-HIST-V1", "dataset_id": "BINANCE-SPOT-BTC-ETH-SOL-UTC-DAILY-OHLCV-TRADES", "source_research_id": "BRRK-LEADERSHIP-ROTATION-0048", "source_dataset_declaration_path": "research/brrk_leadership_rotation_0048/DATASET_DECLARATION.json", "source_market_evidence_path": "research/brrk_beta_handoff_0047/evidence/MARKET_EVIDENCE.json", "source_market_evidence_blob_sha": "64ebf5c6deaf3f34dbeac715378f196ff0f4fafe", "source_loader_path": "research/brrk_beta_handoff_0047/engine.py", "source_loader_blob_sha": "059b55961e279dab41ba29b5b017de0922e4f33c", "source_payload_sha256": "d1cd28bc76f2cd8ee0486287fc50b49e5451355a3e75132a2de5b30c15af3193", "source_common_rows": 2183, "source_common_start": "2020-08-11T00:00:00Z", "source_common_end": "2026-08-02T00:00:00Z", "resolution": "1D", "semantic_timezone": "UTC", "source_index_representation": "UTC_NORMALIZED_TZ_NAIVE_DAILY_DATES", "assets_consumed_by_0059": ["BTC","ETH","SOL"], "field_consumed_by_0059": "daily_close", "network_fetch_allowed": False, "replacement_allowed": False, "synthetic_fill_allowed": False, "researcher_exposed_history": True, "contamination_state": "RESEARCHER_EXPOSED_HISTORY", "data_budget": "DEVELOPMENT", "independent_oos": False},
  "nominal_calendar_derivation": {"max_trend_horizon_days": 240, "causal_normalization_window_days": 252, "causal_normalization_min_valid_raw_observations": 60, "nominal_first_raw_trend_valid": "2021-04-08T00:00:00Z", "nominal_first_joint_normalized_state_origin": "2021-06-06T00:00:00Z", "max_forward_target_days": 240, "nominal_last_shared_origin": "2025-12-05T00:00:00Z", "nominal_shared_origin_count": 1644, "derivation_uses_calendar_and_formulas_only": True, "no_0059_target_value_or_association_read_for_derivation": True},
  "actual_evaluation_slice_policy": {"shared_complete_case_origins_only": True, "all_four_horizons_use_identical_origins": True, "pairwise_or_horizon_specific_dropping_allowed": False, "G1_min_shared_origins": 1440, "actual_origin_count_and_dates_measured_only_at_unique_execution": True},
  "exposure_policy": {"new_raw_data_release_created_by_0059_prereg": False, "existing_exposed_history_reused": True, "independent_oos_claim_allowed": False, "production_evidence_claim_allowed": False, "real_target_values_during_preregistration": False, "real_association_metrics_during_preregistration": False, "real_target_values_during_implementation_only": False}
}

readme = '''# BRRK-BETA-DETERIORATION-BTC-TAKEOVER-DIAGNOSTIC-0059

Status: **NUMERICAL/DATA PREREGISTRATION FROZEN / NOT IMPLEMENTED / NOT RUN**

0059 is a pure DEVELOPMENT mechanism diagnostic. It freezes one equal-weight three-axis causal deterioration state and asks whether it has recurrent monotone information about future BTC-over-Beta continuation value simultaneously at 20/60/120/240 days. It defines no trading threshold, allocation map, switching rule, NAV path, transaction-cost model or production action.

Primary gates are: G1 shared support >=1440; G2 all four full-sample Spearman correlations >0; G3 at least 3/4 chronological blocks positive at all four horizons; G4 all four simultaneous one-sided 95% LCBs >0 under aligned non-circular moving-block bootstrap length 240, 10000 reps, seed 1844716895, Type-7 quantile.

0058 remains immutable FAIL_NO_STABLE_PARAMETER_PLATEAU and its exposed `(120,0.50)` maximum has zero 0059 authority. 0057 ETH/SOL micro-timing remains closed. BTC-to-cash is not opened.

No real 0059 target, correlation, bootstrap or portfolio output may be computed during preregistration or implementation-only. After prereg merge, the next legal stage is implementation-only with synthetic/toy/contract tests. A separate controlled-execution boundary must merge before the unique historical DEVELOPMENT execution. A future PASS only makes a new-ID translation/calibration study eligible; it cannot freeze a trading parameter or modify canonical/production authority.
'''

registry = json.loads(REGISTRY.read_text(encoding='utf-8'))
records = registry.get('records')
if not isinstance(records, list): raise SystemExit('registry records missing')
if any(isinstance(x, dict) and x.get('research_id') == RID for x in records): raise SystemExit('0059 owner already exists')
records.append(record)
REGISTRY.write_text(json.dumps(registry, indent=2, ensure_ascii=False) + '\n', encoding='utf-8')

if OUT.exists(): raise SystemExit('0059 formal path already exists')
OUT.mkdir(parents=True)
(OUT/'PREREGISTRATION.json').write_text(json.dumps(prereg, indent=2, ensure_ascii=False)+'\n', encoding='utf-8')
(OUT/'DATASET_DECLARATION.json').write_text(json.dumps(dataset, indent=2, ensure_ascii=False)+'\n', encoding='utf-8')
(OUT/'README.md').write_text(readme, encoding='utf-8')

s = STATE.read_text(encoding='utf-8')
old_branch = 'Current research branch: **`research/0059-beta-deterioration-btc-takeover-diagnostic-design`**  '
new_branch = 'Current research branch: **`research/0059-beta-deterioration-btc-takeover-diagnostic-prereg`**  '
if old_branch not in s: raise SystemExit('CURRENT_STATE branch anchor missing')
s = s.replace(old_branch, new_branch, 1)
old_exec = 'BRRK Beta deterioration/BTC takeover 0059 DESIGN FROZEN / PREREG ABSENT / NOT RUN'
new_exec = 'BRRK Beta deterioration/BTC takeover 0059 NUMERICAL PREREG FROZEN / NOT IMPLEMENTED / NOT RUN'
if old_exec not in s: raise SystemExit('CURRENT_STATE executive anchor missing')
s = s.replace(old_exec, new_exec, 1)
if '## 0059 numerical/data preregistration handoff' in s: raise SystemExit('prereg handoff already present')
s = s.rstrip() + '''\n\n---\n\n## 0059 numerical/data preregistration handoff\n\n`BRRK-BETA-DETERIORATION-BTC-TAKEOVER-DIAGNOSTIC-0059` now has a durable `PROGRAM_GOVERNED_V1` owner and frozen numerical/data preregistration. **No 0059 historical target value, association metric, bootstrap result or portfolio economic output has been computed.**\n\n```text\ndesign merge                           444e0ee6422e541e3d602ca0272200217834e6d8\nstage                                  NUMERICAL/DATA PREREG FROZEN / NOT IMPLEMENTED / NOT RUN\ndataset                                BRRK-LEADERSHIP-ROTATION-0048-EXPOSED-HIST-V1\npayload SHA256                         d1cd28bc76f2cd8ee0486287fc50b49e5451355a3e75132a2de5b30c15af3193\nhistory                                RESEARCHER_EXPOSED / DEVELOPMENT / NOT INDEPENDENT OOS\nnominal shared origins                 1644 / 2021-06-06..2025-12-05\nG1 minimum actual shared origins       1440\nG2                                     all four full-sample Spearman rho > 0\nG3                                     >=3/4 chronological blocks positive at all four horizons\nbootstrap                              non-circular moving block / length 240 / 10000 / seed 1844716895\nG4                                     all four simultaneous one-sided 95% LCB > 0\nactual variants evaluated              0\nportfolio economics                    FORBIDDEN UNDER 0059\n```\n\nFrozen future outcomes use `Y_h=log(W_BTC/W_BETA)` for h=20/60/120/240 with origin-reset arithmetic `W_BETA=0.5*ETH[t+h]/ETH[t]+0.5*SOL[t+h]/SOL[t]`; all horizons share one complete-case origin set. The 240-origin dependence block is fixed from the longest preregistered forward-target overlap, not from results.\n\n0058 remains immutable `FAIL_NO_STABLE_PARAMETER_PLATEAU / CLOSED`; its `(120,0.50)` descriptive maximum and local geometry have zero 0059 authority. 0057 micro-timing remains closed. BTC-to-cash is not opened.\n\nClassification precedence is `INVALID_EXECUTION -> FAIL_INSUFFICIENT_CAUSAL_SUPPORT -> FAIL_NO_MONOTONE_CONTINUATION_INFORMATION -> FAIL_TEMPORAL_INSTABILITY -> FAIL_DEPENDENCE_AWARE_ROBUSTNESS -> PASS_MECHANISM_INFORMATION_STAGE_ELIGIBLE`. PASS only permits a new-ID translation/calibration study.\n\n**Exact next step after prereg merge:** implementation-only with synthetic/toy/contract tests. Real market loading and all 0059 historical targets/correlations remain forbidden until a separately merged controlled-execution boundary.\n''' + '\n'
STATE.write_text(s, encoding='utf-8')
